image: node:8

before_script:
  - 'which ssh-agent || (apt-get update -y && apt-get install openssh-client -y)'
  - 'which tar || (apt-get update -y && apt-get install tar -y)'
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  - echo $SSH_PUBLIC_KEY > /root/.ssh/id_rsa.pub
  - echo $SSH_PRIVATE_KEY > /root/.ssh/id_rsa
  - chmod 0600 /root/.ssh/id_rsa.pub
  - chmod 0600 /root/.ssh/id_rsa
  - '[[ -f /.dockerenv ]] && echo "$SSH_SERVER_HOSTKEYS" > ~/.ssh/known_hosts'
  - rm -rf node_modules
  - npm install -g yarn
  - yarn

jest_react_tests:
  script:
    - yarn test
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/

after_script:
  - yarn build
  - tar -cvf build.zip build/
  - scp -vvv build.zip bogdan.calapod@systems.cs.pub.ro:/var/www/systems.cs.pub.ro/www/
  - ssh -t bogdan.calapod@systems.cs.pub.ro "cd /var/www/systems.cs.pub.ro/www/ && tar -xzvf build.zip -C ./ && exit"
