name: Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup rust tools
        run: ./setup_rust_tools.sh
      - name: setup node
        uses: actions/setup-node@v3
        
      - name: build rust
        working-directory: ./rust-project
        run: cargo build --verbose
      - name: run rust
        working-directory: ./rust-project
        env: 
          SERVICE_ACCOUNT_PRIVATE_KEY: ${{ secrets.SERVICE_ACCOUNT_PRIVATE_KEY }}
        run: cargo run --verbose
      
      - name: build
        run: yarn && yarn build
      - name: upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./build
      - name: deploy
        id: deployment
        uses: actions/deploy-pages@v2
